CREATE TABLE JS156724.COMMUNITYBOARD
(
    BoardID INT CONSTRAINT PK_COMMUNITYBOARD_BOARDID PRIMARY KEY,
    Username VARCHAR(20) NOT NULL,
    Title VARCHAR(255),
    Description VARCHAR(255),
    CreationTimestamp DATETIME,
    Comments VARCHAR(200),
    CONSTRAINT PK_COMMUNITYBOARD_USERNAME FOREIGN KEY (Username) REFERENCES JS156724.USERS(Username)
)