CREATE TABLE JS156724.DEVELOPER
(
    DevID INT CONSTRAINT PK_DEVELOPER_DEVID PRIMARY KEY,
    DevNames VARCHAR(255) NOT NULL,
    WebsiteName VARCHAR(255),
    NewsBoard VARCHAR(500),
    PublishedGames INT

)