CREATE TABLE JS156724.FILTER
(
    FilterID INT CONSTRAINT PK_FILTER_FILTERID PRIMARY KEY ,
    Username VARCHAR(20) NOT NULL ,
    CONSTRAINT FK_FILTER_USERNAME FOREIGN KEY (Username) REFERENCES JS156724.USERS(Username),
    FilterTypes VARCHAR(20),
    PlatformFilter VARCHAR(100),
)