CREATE TABLE JS156724.GAMELIBRARY
(
    LibraryID INT NOT NULL CONSTRAINT PK_GAMELIBRARY_LIBRARYID PRIMARY KEY,
    Username VARCHAR(20) NOT NULL,
    CONSTRAINT FK_GAMELIBRARY_USERNAME FOREIGN KEY(Username) REFERENCES JS156724.USER(Username),
    Game VARCHAR(50) NOT NULL,
    CONSTRAINT FK_GAMELIBRARY_GAME FOREIGN KEY(Game) REFERENCES JS156724.GAME(GameName)


)