CREATE TABLE JS156724.TICKETS
(
    TicketID INT CONSTRAINT PK_TICKETS_TICKETID PRIMARY KEY,
    TicketName varchar(50),
    TicketContext varchar(255),
    Username VARCHAR(20) NOT NULL ,
    StaffID INT NOT NULL ,
    CONSTRAINT PK_TICKETS_USERNAME FOREIGN KEY (Username) REFERENCES JS156724.USER(Username),
    CONSTRAINT PK_TICKETS_STAFFID FOREIGN KEY (StaffID) REFERENCES JS156724.STAFF(StaffID)
)