CREATE TABLE JS156724.USERS
(
    Username VARCHAR(20) NOT NULL CONSTRAINT PK_USERS_USERNAME PRIMARY KEY,
    Password VARCHAR(40) NOT NULL,
    Location VARCHAR(100),
    Wishlist VARCHAR(200),
    Email VARCHAR(255) NOT NULL UNIQUE,
    PreferredGenre VARCHAR(30),
    CONSTRAINT FK_USERS_PREFERREDGENRE FOREIGN KEY(PreferredGenre) REFERENCES JS156724.GENRES(Name)
)