CREATE TABLE JS156724.WALLET
(
    Username VARCHAR(20) NOT NULL CONSTRAINT PK_WALLET_USERNAME PRIMARY KEY,
    Balance DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_WALLET_USERNAME FOREIGN KEY(Username) REFERENCES JS156724.USERS(Username)
)